version: '3'

networks:
  backend:
  frontend:

services:

  ### reverse-proxy #########################################
  payflow:
    container_name: payflow
    networks:
      - frontend
      - backend
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ../:/usr/share/nginx/html/payflow

  ### PHP-FPM ##############################################
  php-fpm:
    container_name: php
    networks:
      - backend
    #image: php:7.3.6-fpm
    build: ./php
    expose:
      - 9000
    volumes:
      - ../:/usr/share/nginx/html/payflow

  ### database ##############################################
  database:
    container_name: mysql
    networks:
      - backend
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cart
      MYSQL_USER: default
      MYSQL_PASSWORD: secret
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql/local.cnf:/etc/mysql/conf.d/local.cnf
      - ./mysql/data:/docker-entrypoint-initdb.d

  ### phpMyAdmin ###########################################
  phpmyadmin:
    container_name: phpmyadmin
    networks:
      - frontend
      - backend
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8888:80"
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_USER=default
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=root
    depends_on:
      - "database"


